name: Main

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Create .env file
        working-directory: ./app
        run: cp .env.example .env

      - name: Validate composer.json and composer.lock
        working-directory: ./app
        run: composer validate --strict

      - name: Install dependencies
        working-directory: ./app
        run: composer install --prefer-dist --no-progress

  php-cs-fixer:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PHP CS Fixer
        uses: docker://ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.3
        with:
          args: fix app/src --config=app/.php-cs-fixer.dist.php --dry-run --diff

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        working-directory: ./app
        run: cp .env.example .env

      - name: Install dependencies
        working-directory: ./app
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        working-directory: ./app
        run: ./vendor/codeception/codeception/codecept run Unit
